/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public void show(){
        System.out.println("==>show");
    }
}
